### File: .github/workflows/build.yml ###
name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:    # Allows manual trigger from GitHub UI

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller keyboard
    
    - name: Build executable
      run: pyinstaller --onefile --windowed numkey_gui.py
    
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: numkey-gui
        path: dist/numkey_gui.exe

### File: requirements.txt ###
keyboard==0.13.5
tkinter

### File: .gitignore ###
# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
*.egg-info/
.installed.cfg
*.egg

# PyInstaller
dist/
build/

# Application specific
numkey_state.json
